let aliases = {
    "allosaurus": "Аллозавр",
    "carnotaurus": "Карнотавр",
    "compy": "Компсогнат",
    "dilophosaur": "Дилофозавр",
    "giganotosaurus": "Гиганотозавр",
    "megalosaurus": "Мегалозавр",
    "microraptor": "Микрораптор",
    "oviraptor": "Овираптор",
    "raptor": "Раптор",
    "rex": "Тираннозавр",
    "spinosaur": "Спинозавр",
    "troodon": "Троодон",
    "velonasaur": "Велоназавр",
    "yutyrannus": "Ютираннус",
    "ankylosaurus": "Анкилозавр",
    "brontosaurus": "Бронтозавр",
    "diplodocus": "Диплодок",
    "gallimimus": "Галлимим",
    "iguanodon": "Игуанодон",
    "kentrosaurus": "Кентрозавр",
    "morellatops": "Морелатопс",
    "pachy": "Пахицефалозавр",
    "pachyrhinosaurus": "Пахиринозавр",
    "parasaur": "Паразауролоф",
    "pegomastax": "Пегомастакс",
    "stegosaurus": "Стегозавр",
    "therizinosaurus": "Теризинозавр",
    "polarbear": "Полярный Медведь",
    "titanosaur": "Титанозавр",
    "triceratops": "Трицератопс",
    "baryonyx": "Барионикс",
    "basilosaurus": "Базилозавр",
    "dimetrodon": "Диметродон",
    "direwolf": "Лютоволк",
    "hyaenodon": "Гиенодон",
    "purlovia": "Пурловия",
    "rollrat": "Кротокрыс",
    "sabertooth": "Саблезуб",
    "thylacoleo": "Сумчатый Лев",
    "castoroides": "Кастороидес",
    "chalicotherium": "Халикотерий",
    "doedicurus": "Дедикурус",
    "equus": "Эквус",
    "gigantopithecus": "Гигантопитек",
    "jerboa": "Тушканчик",
    "lystrosaurus": "Листрозавр",
    "mammoth": "Мамонт",
    "megaloceros": "Большерогий Олень",
    "ovis": "Овис",
    "paraceratherium": "Парацератерий",
    "paracer": "Парацератерий",
    "phiomia": "Фиомия",
    "procoptodon": "Прокоптодон",
    "woollyrhino": "Шерстистый Носорог",
    "daeodon": "Деодон",
    "direbear": "Свирепый Медведь",
    "megatherium": "Мегатерий",
    "mesopithecus": "Мезопитек",
    "moschops": "Мосхопс",
    "onyc": "Оник",
    "otter": "Выдра",
    "beelzebufo": "Жаба",
    "carbonemys": "Карбонемис",
    "diplocaulus": "Диплокаулус",
    "kaprosuchus": "Капрозух",
    "megalania": "Мегалания",
    "sarco": "Саркозух",
    "thornydragon": "Шипастый Дракон",
    "titanoboa": "Титанобоа",
    "ichthyosaurus": "Ихтиозавр",
    "liopleurodon": "Лиоплевродон",
    "mosasaurus": "Мозазавр",
    "plesiosaur": "Плезиозавр",
    "dimorphodon": "Диморфодон",
    "pteranodon": "Птеранодон",
    "quetzal": "Кетцалькоатль",
    "tapejara": "Тапежара",
    "dodo": "Додо",
    "hesperornis": "Гесперорнис",
    "kairuku": "Кайруку",
    "terrorbird": "Ужасная Птица",
    "archaeopteryx": "Археоптерикс",
    "argentavis": "Аргентавис",
    "ichthyornis": "Ихтиорнис",
    "pelagornis": "Пелагорнис",
    "snowowl": "Снежная Сова",
    "vulture": "Гриф",
    "angler": "Удильщик",
    "coelacanth": "Целакант",
    "dunkleosteus": "Дунклеостей",
    "electrophorus": "Электрофорус",
    "leedsichthys": "Лидсихтис",
    "manta": "Манта",
    "megalodon": "Мегалодон",
    "piranha": "Пиранья",
    "achatina": "Ахатина",
    "mantis": "Богомол",
    "pulmonoscorpius": "Скорпион",
    "araneo": "Аранео",
    "arthropluera": "Артроплевра",
    "dungbeetle": "Скарабей",
    "giantbee": "Гигантская Пчела",
    "lymantria": "Шелкопряд",
    "tusoteuthis": "Тусотеутис",
    "bulbdog": "Лампадог",
    "glowtail": "Лучехвост",
    "ravager": "Опустошитель",
    "rockelemental": "Горный Элементаль",
    "chalkgolem": "Меловой Голем",
    "icegolem": "Ледяной Голем",
    "shinehorn": "Светорог",
    "basilisk": "Василиск",
    "featherlight": "Яснокрыл",
    "gacha": "Гача",
    "gasbags": "Газбагс",
    "griffin": "Грифон",
    "managarmr": "Манагарм",
    "phoenix": "Феникс",
    "rockdrake": "Скальный Дрейк",
    "wyvern": "Виверна",
    "icewyvern": "Ледяная Виверна",
    "karkinos": "Каркинос",
    "enforcer": "Инфорсер",
    "mek": "Мех",
    "megamek": "Мега Мех",
    "scout": "Разведчик",
    "reaper": "Королева Жнецов",
    "ammonite": "Аммонит",
    "cnidaria": "Книдария",
    "eurypterid": "Ракоскорпион",
    "leech": "Пиявка",
    "meganeura": "Меганевра",
    "sabertooth_salmon": "Саблезубый Лосось",
    "titanomyrma": "Титаномуравей",
    "trilobite": "Трилобит",
    "deathworm": "Червь Смерти",
    "jugbug": "Жук-кувшинчик",
    "glowbug": "Светлячок",
    "lamprey": "Минога",
    "nameless": "Безымянный",
    "seeker": "Искатель",
    "deinonychus": "Дейноних",
};

module.exports = aliases;
